# Top of file
version: 2
jobs: 
  build:
    docker:
      - image: circleci/golang:1.11.1
    working_directory: /go/src/github.com/sid/circleci-hello
    steps:
      - checkout # Checks out the source code
      - run: echo "hello world"
      - run: 
          name: Build the executable
          command:
            echo "Other important command here as example"
            go build 
      - persist_to_workspace:
          root: . # persist current working directory
          paths: ./* # glob will persist everything
      - store_artifacts:
          path: ./circleci-hello # executable

  test:
    docker:
      - image: circleci/golang:1.11.1
    working_directory: /go/src/github.com/sid/circleci-hello
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: echo "hello 2"
      - run: go test

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build